package io.eel.eel_runner_infra_provisioner_core.stacks.model;

public enum ResourceType {

    // AWS resource types
    AWS_IAM_ROLE_NAME,
    AWS_IAM_ROLE_ARN,
    AWS_IAM_POLICY_ARN,
    AWS_IAM_POLICY_NAME,
    AWS_SCHEDULER_NAME,
    AWS_S3_BUCKET_NAME,
    AWS_S3_BUCKET_ARN,
    AWS_LAMBDA_FUNCTION_NAME,
    AWS_SQS_INPUT_QUEUE_URL,
    AWS_SQS_INPUT_QUEUE_ARN,
    AWS_SQS_DEAD_LETTER_QUEUE_URL,
    AWS_SQS_DEAD_LETTER_QUEUE_ARN,
    AWS_STEP_FUNCTION_ARN,
    AWS_LAMBDA_EVENT_SOURCE_MAPPING_UUID,

    // GCP resource types
    GCP_IAM_ROLE,
    GCP_IAM_POLICY,
    GCP_SCHEDULER,
    GCP_BUCKET,
    GCP_CLOUD_FUNCTION,
    GCP_PUB_SUB_INPUT_QUEUE_URL,
    GCP_PUB_SUB_DEAD_LETTER_QUEUE_URL

}