package io.eel.flow_api_aws_lambda.dao;

import io.eel.common.model.*;
import io.eel.common_aws.BaseAwsDynamoDbDao;
import io.eel.flow_api_core.dao.FlowDao;
import org.apache.commons.lang3.RandomStringUtils;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;
import software.amazon.awssdk.services.dynamodb.model.PutItemRequest;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;
import software.amazon.awssdk.services.s3.presigner.S3Presigner;
import software.amazon.awssdk.services.s3.presigner.model.PresignedPutObjectRequest;
import software.amazon.awssdk.services.s3.presigner.model.PutObjectPresignRequest;

import java.io.File;
import java.nio.file.Path;
import java.time.Duration;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.function.Function;

public class AwsDynamoDbFlowDaoImpl extends BaseAwsDynamoDbDao<Flow, UUID> implements FlowDao {

    private static final String TABLE_NAME = "eel-flows";

    private static final String PARTITION_KEY = "id";

    private static final int PRESIGNED_URL_EXPIRATION_IN_HOURS = 8; // One business day.

    // todo:  Make this an environment variable that is generated by IaC.
//    private static final String STAGING_BUCKET_NAME = String.format("eel-staging-bucket-%s", RandomStringUtils.randomAlphanumeric(8));
    private static final String STAGING_BUCKET_NAME = "eel-staging-bucket-sljf34fa";

    private static final Function<Map<String, AttributeValue>, Flow> DYNAMO_DB_ITEM_MAPPER = (item) -> new Flow(
            UUID.fromString(item.get("id").s()),
            Integer.parseInt(item.get("version").n()),
//            item.get("author").s(),
//            InputType.valueOf(item.get("inputType").s()),
            null, // todo:  fix this.
            null, // todo:  fix this.
            new ScheduledBatchConfiguration(null, null, null, null, null), // todo:  fix this.
            new StreamingConfiguration(null), // todo:  fix this.
            new OutputConfiguration(null, null, null), // todo:  fix this.
            item.get("isFinalized").bool()
    );

    public AwsDynamoDbFlowDaoImpl(DynamoDbClient dynamoDbClient) {
        super(dynamoDbClient, TABLE_NAME, PARTITION_KEY);
    }

    public void saveFileToS3(Path path) {
        S3Client s3Client = S3Client.create();

        var request = PutObjectRequest.builder()
                .bucket(STAGING_BUCKET_NAME)
                .key("test")
                .build();

        s3Client.putObject(request, path);
    }

    /**
     * This is a custom DAO method to retrieve all flows IDs for a given username.
     * @param userName {@link String}
     * @return {@link Set<UUID>}
     */
    @Override
    public Set<UUID> getFlowsByUser(String userName) {
        return Set.of(); // todo:  add logic for this custom method.
    }

    /**
     * This is a thin wrapper around {@link BaseAwsDynamoDbDao#getById(Object, Function)}
     * @param id {@link UUID}
     * @return {@link Optional<Flow>}
     */
    @Override
    public Optional<Flow> getFlowById(UUID id) {
        return super.getById(id, DYNAMO_DB_ITEM_MAPPER);
    }

    @Override
    public Flow updateFlow(Flow flow) {
        return super.save(
                flow,
                f -> AttributeValue.fromS(f.getId().toString())
        );
    }

    @Override
    public Flow createNewFlow(String author) {
        final Flow flow = Flow.create(author);
        final String transformationStagingUrl = this.generateTransformationStagingPresignedUrl(flow.getId());
        flow.updateTransformationStagingUrl(
                new FlowInitDto(flow.getId(), flow.getVersion(), transformationStagingUrl)
        );

        return super.save(
                flow,
                f -> AttributeValue.fromS(f.getId().toString())
        );
    }

    @Override
    public String generateTransformationStagingPresignedUrl(UUID flowId) {
        try (S3Presigner preSigner = S3Presigner.create()) {
            PutObjectRequest objectRequest = PutObjectRequest.builder()
                    .bucket(STAGING_BUCKET_NAME)
                    .key(flowId.toString())
                    .contentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                    .build();

            PutObjectPresignRequest presignRequest = PutObjectPresignRequest.builder()
                    .signatureDuration(Duration.ofHours(PRESIGNED_URL_EXPIRATION_IN_HOURS))
                    .putObjectRequest(objectRequest)
                    .build();

            PresignedPutObjectRequest presignedRequest = preSigner.presignPutObject(presignRequest);

            String url = presignedRequest.url().toString();
            System.out.println("Presigned URL to upload a file to: " + url);
            System.out.println("HTTP method: " + presignedRequest.httpRequest().method());
            System.out.println("Presigned external URL to a upload file to: " + presignedRequest.url().toExternalForm());

            return url;
        }
    }

}
